spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# 1. Cambia 'create' por 'create-drop' o déjalo en 'create' si quieres que borre y meta los datos de data.sql en cada reinicio
spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true

# 2. ESTO ES CRUCIAL: Le dice a Spring que ejecute data.sql DESPUÉS de que Hibernate cree las tablas
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always